### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by M-DinhHoangViet** [ianfab/stockfish.wasm#13]
This supports pychess, does it support lichess or playstrategy?

**Comment by ianfab** [comment]
Whether they use it is their decision, but of course any website could use it. For playstrategy [I suggested to use it](https://github.com/Mind-Sports-Games/lila/issues/588), for lichess I think the motivation to switch from MV-SF is not that strong considering that they do not plan to add new variants, since the JS version of MV-SF they use has a similar level as Fairy-SF without NNUE for their existing variants (in the range of +-300 Elo), so switching would only be important if they wanted to enable NNUE, since that would give a boost in playing strength, but I think they are rather conservative about introducing complexity for the niche feature of variants.
